server:
  extraArgs:
    - --insecure
  extensions:
    # -- Enable support for extensions
    ## This function in tech preview stage, do expect unstability or breaking changes in newer versions. Bump image.tag if necessary.
    enabled: true

    # -- Extensions to be loaded into the server
    contents: 
    - name: argo-rollouts
      url: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.1.0/extension.tar

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: istio
  
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        prometheus: primary

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        prometheus: primary

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        prometheus: primary
