secret:
  enabled: false

ingress:
  public:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      # TODO: move to variables
      - host: app.dev.dzhurybida.com
        paths:
          - path: /api/kratos(/|$)(.*)
            pathType: ImplementationSpecific

kratos:
  development: false
  # -- Enable the initialization job. Required to work with a DB
  autoMigrate: true
  config:
    tracing:
      provider: zipkin
      providers:
        zipkin:
          server_url: http://tempo.observability:9411/api/v2/spans

    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: file:///etc/config/identity.default.schema.json

    selfservice:
    # TODO
      default_browser_return_url: http://app.dev.dzhurybida.com/

  identitySchemas:
   "identity.default.schema.json": |
    {
      "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Person",
      "type": "object",
      "properties": {
        "traits": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "format": "email",
              "title": "E-Mail",
              "minLength": 3,
              "ory.sh/kratos": {
                "credentials": {
                  "password": {
                    "identifier": true
                  }
                },
                "verification": {
                  "via": "email"
                },
                "recovery": {
                  "via": "email"
                }
              }
            },
            "name": {
              "type": "object",
              "properties": {
                "first": {
                  "title": "First Name",
                  "type": "string"
                },
                "last": {
                  "title": "Last Name",
                  "type": "string"
                }
              }
            }
          },
          "required": [
            "email"
          ],
          "additionalProperties": false
        }
      }
    }
  