loki:
  enabled: true
  persistence:
    enabled: true
    storageClassName: do-block-storage
    accessModes: ["ReadWriteOnce"]
    size: 5Gi


promtail:
  enabled: true
  pipelineStages:
  - cri: {}
  serviceMonitor:
    enabled: true

grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: false