apiVersion: 1
datasources:
- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  version: 1
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: "trace_id\": \"(\w+)"
        name: TraceID
        # url will be interpreted as query for the datasource
        url: "$${__value.raw}"