apiVersion: 1
datasources:
- name: Loki
  type: loki
  uid: my_loki
  access: proxy
  url: http://loki:3100
  isDefault: false
  editable: true
  version: 1
  jsonData:
    derivedFields:
      - datasourceUid: my_tempo
        matcherRegex: "trace_id\\\": \\\"(\\w+)"
        name: Tempo
        # url will be interpreted as query for the datasource
        url: "${__value.raw}"
