loki:
  enabled: true
  persistence:
    enabled: true
    storageClassName: do-block-storage
    accessModes: ["ReadWriteOnce"]
    size: 5Gi

  serviceMonitor:
    enabled: true
    additionalLabels:
      prometheus: primary


promtail:
  enabled: true
  pipelineStages:
  - cri: {}
  serviceMonitor:
    enabled: true
    labels:
      prometheus: primary

grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: false