
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: counter-app-rule
  namespace: counter
spec:
  upstream:
    url: http://counter-app.counter/
  match:
    url: <http|https>://app.dev.dzhurybida.com/counter/<.*>
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
  authenticators:
    - handler: cookie_session
    - handler: bearer_token
  authorizer:
    handler: allow
  mutators:
    - handler: header
    - handler: id_token
