commonLabels:
  prometheus: primary

prometheus:
  prometheusSpec:
    podMonitorSelector:
      matchLabels:
        prometheus: primary
    podMonitorNamespaceSelector:
      matchLabels:
        monitoring: enabled
    serviceMonitorSelector:
      matchLabels:
        prometheus: primary
    serviceMonitorNamespaceSelector:
      matchLabels:
        monitoring: enabled
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: do-block-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      # cert-manager.io/cluster-issuer: letsencrypt-prod
    # tls:
    # - secretName: grafana-general-tls

  persistence:
    enabled: true
    storageClassName: do-block-storage
    accessModes: ["ReadWriteOnce"]
    size: 5Gi

## Create default rules for monitoring the cluster
##
## Disable `etcd` and `kubeScheduler` rules (managed by DOKS, so metrics are not accessible)
##
defaultRules:
  rules:
    etcd: false
    kubeScheduler: false

## Component scraping kube scheduler
##
## Disabled because it's being managed by DOKS, so it's not accessible
##
kubeScheduler:
  enabled: false

## Component scraping etcd
##
## Disabled because it's being managed by DOKS, so it's not accessible
##
kubeEtcd:
  enabled: false