persistence:
  enabled: true
  storageClassName: do-block-storage
  accessModes: ["ReadWriteOnce"]
  size: 5Gi


serviceMonitor:
  enabled: true
  additionalLabels:
    prometheus: primary

tempo:
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_binary:
          endpoint: 0.0.0.0:6832
        thrift_compact:
          endpoint: 0.0.0.0:6831
        thrift_http:
          endpoint: 0.0.0.0:14268
    zipkin:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"