apiVersion: 1
datasources:
- name: Tempo
  type: tempo
  uid: my_tempo
  access: proxy
  editable: true
  url: http://tempo:3100
  version: 1
  jsonData:
    nodeGraph:
      enabled: true
    tracesToLogs:
      datasourceUid: my_loki
      filterByTraceID: true
      mapTagNamesEnabled: true
      mappedTags:
      - key: service.name
        value: app_kubernetes_io_name