apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-app-base
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: counter
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/counter
    repoURL: https://github.com/DZhuribeda/cluster-config.git
    targetRevision: HEAD